import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { Alert, FlatList, Modal, Pressable, StyleSheet, Switch, Text, TextInput, View } from "react-native";

import { Badge, Card, COLORS, PrimaryButton } from "@/components/agent-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useAgentState, type MemoryEntry } from "@/lib/agent-state";

export default function MemoryScreen() {
  const { memories, addMemory, updateMemory, removeMemory } = useAgentState();
  const [visible, setVisible] = useState(false);
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [category, setCategory] = useState("偏好");
  const save = () => { if (!title.trim() || !content.trim()) { Alert.alert("请填写记忆", "标题和内容均为必填项。"); return; } addMemory({ title, content, category }); setTitle(""); setContent(""); setCategory("偏好"); setVisible(false); };
  return <ScreenContainer className="p-0" containerClassName="bg-background"><FlatList data={memories} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} renderItem={({ item }) => <MemoryCard item={item} onToggle={() => updateMemory(item.id, { enabled: !item.enabled })} onDelete={() => Alert.alert("删除本地记忆", `确定删除“${item.title}”吗？`, [{ text: "取消", style: "cancel" }, { text: "删除", style: "destructive", onPress: () => removeMemory(item.id) }])} />} ListHeaderComponent={<View><View style={styles.headerRow}><View style={styles.headerText}><Text style={styles.title}>本地记忆</Text><Text style={styles.subtitle}>在设备内保存可检索的偏好与上下文，仅将匹配标题写入任务轨迹。</Text></View><Pressable onPress={() => setVisible(true)} style={({ pressed }) => [styles.addButton, pressed && styles.pressed]}><MaterialIcons name="add" size={21} color={COLORS.background} /></Pressable></View><Card style={styles.infoCard}><MaterialIcons name="memory" size={20} color={COLORS.blue} /><Text style={styles.infoText}>记忆默认只保存在本机。任务会自动检索已启用的匹配记忆，不会将完整内容写入运行记录。</Text></Card></View>} ListEmptyComponent={<Card style={styles.emptyCard}><MaterialIcons name="psychology" size={27} color={COLORS.muted} /><Text style={styles.emptyTitle}>创建第一条记忆</Text><Text style={styles.emptyText}>保存工作偏好、项目背景或执行约束，使后续任务获得更一致的上下文。</Text></Card>} /><MemoryModal visible={visible} title={title} content={content} category={category} onTitle={setTitle} onContent={setContent} onCategory={setCategory} onClose={() => setVisible(false)} onSave={save} /></ScreenContainer>;
}

function MemoryCard({ item, onToggle, onDelete }: { item: MemoryEntry; onToggle: () => void; onDelete: () => void }) { return <Card style={[styles.memoryCard, !item.enabled && styles.memoryCardDisabled]}><View style={styles.memoryTop}><View style={styles.memoryIcon}><MaterialIcons name="psychology" size={21} color={item.enabled ? COLORS.mint : COLORS.muted} /></View><View style={styles.memoryText}><Text style={styles.memoryTitle}>{item.title}</Text><Text numberOfLines={3} style={styles.memoryContent}>{item.content}</Text></View><Switch value={item.enabled} onValueChange={onToggle} trackColor={{ false: "#294454", true: "#27796E" }} thumbColor={item.enabled ? COLORS.mint : "#9AAEBB"} /></View><View style={styles.memoryFooter}><Badge label={item.category} tone="info" /><Text style={styles.updatedText}>{item.enabled ? "任务可引用" : "已停用"}</Text><Pressable onPress={onDelete} style={({ pressed }) => [styles.deleteButton, pressed && styles.pressed]}><MaterialIcons name="delete-outline" size={19} color={COLORS.coral} /></Pressable></View></Card>; }

function MemoryModal({ visible, title, content, category, onTitle, onContent, onCategory, onClose, onSave }: { visible: boolean; title: string; content: string; category: string; onTitle: (value: string) => void; onContent: (value: string) => void; onCategory: (value: string) => void; onClose: () => void; onSave: () => void }) { return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.handle} /><View style={styles.sheetHeader}><View><Text style={styles.sheetTitle}>添加本地记忆</Text><Text style={styles.sheetSub}>此内容仅保存在当前设备。</Text></View><Pressable onPress={onClose} style={styles.closeButton}><MaterialIcons name="close" size={20} color={COLORS.text} /></Pressable></View><Field label="标题" value={title} onChangeText={onTitle} placeholder="例如：项目沟通偏好" /><Field label="分类" value={category} onChangeText={onCategory} placeholder="偏好、项目或安全" /><Text style={styles.fieldLabel}>记忆内容</Text><TextInput multiline value={content} onChangeText={onContent} placeholder="记录在任务中需要长期参考的信息…" placeholderTextColor="#7590A0" textAlignVertical="top" style={[styles.input, styles.contentInput]} /><PrimaryButton label="保存本地记忆" icon="save" onPress={onSave} /></View></View></Modal>; }
function Field({ label, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><TextInput style={styles.input} placeholderTextColor="#7590A0" {...props} /></View>; }
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 34 }, headerRow: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" }, headerText: { flex: 1, paddingRight: 14 }, title: { color: COLORS.text, fontSize: 28, fontWeight: "800", letterSpacing: -0.7 }, subtitle: { color: COLORS.muted, fontSize: 13, lineHeight: 19, marginTop: 5 }, addButton: { alignItems: "center", backgroundColor: COLORS.mint, borderRadius: 14, height: 46, justifyContent: "center", width: 46 }, infoCard: { alignItems: "flex-start", flexDirection: "row", gap: 10, marginBottom: 16, marginTop: 17 }, infoText: { color: COLORS.muted, flex: 1, fontSize: 12, lineHeight: 18 }, emptyCard: { alignItems: "center", padding: 25 }, emptyTitle: { color: COLORS.text, fontSize: 15, fontWeight: "800", marginTop: 8 }, emptyText: { color: COLORS.muted, fontSize: 12, lineHeight: 18, marginTop: 4, textAlign: "center" }, memoryCard: { marginBottom: 12 }, memoryCardDisabled: { opacity: 0.66 }, memoryTop: { alignItems: "flex-start", flexDirection: "row", gap: 10 }, memoryIcon: { alignItems: "center", backgroundColor: "#163D3C", borderRadius: 12, height: 42, justifyContent: "center", width: 42 }, memoryText: { flex: 1 }, memoryTitle: { color: COLORS.text, fontSize: 14, fontWeight: "800" }, memoryContent: { color: COLORS.muted, fontSize: 11, lineHeight: 17, marginTop: 4 }, memoryFooter: { alignItems: "center", borderTopColor: COLORS.border, borderTopWidth: 1, flexDirection: "row", gap: 9, marginTop: 12, paddingTop: 10 }, updatedText: { color: COLORS.muted, flex: 1, fontSize: 11 }, deleteButton: { alignItems: "center", height: 30, justifyContent: "center", width: 30 }, overlay: { backgroundColor: "#00000099", flex: 1, justifyContent: "flex-end" }, sheet: { backgroundColor: COLORS.surface, borderColor: COLORS.border, borderTopLeftRadius: 28, borderTopRightRadius: 28, borderWidth: 1, padding: 20, paddingBottom: 28 }, handle: { alignSelf: "center", backgroundColor: "#557184", borderRadius: 99, height: 4, marginBottom: 17, width: 42 }, sheetHeader: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between", marginBottom: 18 }, sheetTitle: { color: COLORS.text, fontSize: 19, fontWeight: "800" }, sheetSub: { color: COLORS.muted, fontSize: 12, marginTop: 4 }, closeButton: { alignItems: "center", backgroundColor: "#1A3344", borderRadius: 99, height: 34, justifyContent: "center", width: 34 }, field: { marginBottom: 14 }, fieldLabel: { color: COLORS.text, fontSize: 12, fontWeight: "700", marginBottom: 7 }, input: { backgroundColor: "#0A1A26", borderColor: COLORS.border, borderRadius: 12, borderWidth: 1, color: COLORS.text, fontSize: 14, minHeight: 47, paddingHorizontal: 12 }, contentInput: { minHeight: 116, paddingTop: 12 }, pressed: { opacity: 0.75, transform: [{ scale: 0.98 }] }, });
